# DEFINICAO DE MERCADO
# LISTAR 20 CARACTERISTICAS DE POSTS VIRAIS
# CTA = Call To Action

NOMES_CARACTERISTICAS = {
    "QUALIDADE 4K", "VIDEO CURTO", "LEGENDA CURTA", "USO DE HASHTAG TREND",
    "AUDIO VIRAL", "CORES VIBRANTES", "PRESENÇA DE ROSTO HUMANO", "*CTA", 
    ""
}
